repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        types: [file, python]
        # only check for unused imports for now, as long as
        # the code is not fully PEP8 compatible
        args: [--select=F401]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
     -  id: mypy
        files: sklearn/
